// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // CLI komutları (db push / migrate) doğrudan bağlantıyı (pooler değil) kullanmalı.
  // Uygulama runtime'ı ise DATABASE_URL (pooled) ile src/lib/prisma.ts üzerinden bağlanır.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
